---
- name: Upload config.json
  template:
    src: "config.json.j2"
    dest: "{{ hedgedoc_base_path }}/config.json"
    owner: "{{ hedgedoc_user }}"
    group: "{{ hedgedoc_group }}"
  notify: restart hedgedoc

- name: Upload .sequelizerc
  template:
    src: ".sequelizerc.j2"
    dest: "{{ hedgedoc_base_path }}/.sequelizerc"
    owner: "{{ hedgedoc_user }}"
    group: "{{ hedgedoc_group }}"
  notify: restart hedgedoc
