---
- name: Create group
  group:
    name: "{{ hedgedoc_group }}"
    state: present

- name: Create user
  user:
    name: "{{ hedgedoc_user }}"
    group: "{{ hedgedoc_group }}"
    create_home: yes
    home: "{{ hedgedoc_base_path }}"
    shell: "/bin/false"
    system: yes

- import_tasks: "install.yml"
- import_tasks: "config.yml"

- name: Upload hedgedoc.service
  template:
    src: "hedgedoc.service"
    dest: "/etc/systemd/system/hedgedoc.service"

- name: Enable/Start hedgedoc service
  systemd:
    name: "hedgedoc.service"
    enabled: yes
    daemon_reload: yes
    state: started
