---
- name: Create group
  group:
    name: "{{ codimd_group }}"
    state: present

- name: Create user
  user:
    name: "{{ codimd_user }}"
    group: "{{ codimd_group }}"
    create_home: yes
    home: "{{ codimd_base_path }}"
    shell: "/bin/bash"

- name: Download package tgz
  get_url:
    url: "{{ codimd_source }}"
    dest: "/tmp/codimd.tar.gz"

- name: Extract package tgz
  unarchive:
    src: "/tmp/codimd.tar.gz"
    dest: "{{ codimd_base_path }}"
    remote_src: yes
  become: yes
  become_user: "{{ codimd_group }}"

- name: Delete package tgz
  file:
    path: "/tmp/codimd.tar.gz"
    state: absent

- import_tasks: build.yml
  when: codimd_build

- name: Install production requirements
  npm:
    path: "{{ codimd_base_path }}"
    production: yes
    state: present
  become: yes
  become_user: "{{ codimd_user }}"
  when: not codimd_build

- name: Upload config.json
  template:
    src: "{{ codimd_config_template_path }}"
    dest: "{{ codimd_base_path }}/config.json"
    owner: "{{ codimd_user }}"
    group: "{{ codimd_group }}"
  notify: restart systemd service

- name: Upload .sequelizerc
  template:
    src: ".sequelizerc.j2"
    dest: "{{ codimd_base_path }}/.sequelizerc"
    owner: "{{ codimd_user }}"
    group: "{{ codimd_group }}"
  notify: restart systemd service

- name: Upload codimd.service
  template:
    src: "codimd.service"
    dest: "/etc/systemd/system/codimd.service"

- name: Upload saml cert
  copy:
    dest: "{{ codimd_saml.idpCertPath | default(codimd_base_path + '/idp_cert.pem') }}"
    content: "{{ codimd_saml.idpCert }}"
  when: codimd_saml is defined

- name: Enable/Start codimd service
  systemd:
    name: "codimd.service"
    enabled: yes
    daemon_reload: yes
    state: started